name: Validate

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validate:
    uses: dornglut/github-workflows/.github/workflows/reusable-python-repository-validate.yml@624cb41adeed21a6461eb838bc7330bd0a5079fd
